wood/wood/urls.py
from django.contrib import admin
from django.urls import path, include

admin.site.site_header = 'wood wide web'
admin.site.site_title = 'wood wide web'
admin.site.index_title = 'Admin'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('wood_core.urls')),
]

wood/wood_core/urls.py
from django.urls import path, include

from .views import (
    atlas_data,
    atlas_page,
    atlas_map,
    media,
    about_page,
    front_page,
)

urlpatterns = [
    path('media/<model>/<int:id>/<int:target>', media, name='wood-media'),
    path('atlas/data/', atlas_data, name='wood-data'),
    path('<lang>/atlas.html', atlas_map, name='wood-atlas'),
    path('<lang>/atlas/<int:pid>.html', atlas_page, name='wood-atlas-tree'),
    path('<lang>/about.html', about_page, name='wood-about'),
    path('<lang>/index.html', front_page, name='wood-index'),
    path('<lang>/', front_page),
]

wood/wood_core/models/ancillary.py
#  Copyright (C) 2018 Atelier Cartographique <contact@atelier-cartographique.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.contrib.gis.db import models

from wood_lingua.models import message_field


class Portrait(models.Model):
    id = models.AutoField(primary_key=True)
    tree = models.ForeignKey(to='wood_core.Tree', on_delete=models.CASCADE)
    monthly = models.BooleanField(default=False)
    body = message_field('portrait_body')


class BaseLink(models.Model):
    class Meta:
        abstract = True

    id = models.AutoField(primary_key=True)
    tree = models.ForeignKey(to='wood_core.Tree', on_delete=models.CASCADE)

wood/wood_core/models/media.py
#  Copyright (C) 2018 Atelier Cartographique <contact@atelier-cartographique.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import unicodedata
import re
from django.contrib.gis.db import models
from django.utils.safestring import mark_safe
from easy_thumbnails.fields import ThumbnailerImageField

from wood_lingua.models import message_field


def slugify(s):
    slug = unicodedata.normalize('NFKD', s)
    slug = slug.lower()
    slug = re.sub(r'[^a-z0-9]+', '_', slug).strip('_')
    slug = re.sub(r'[_]+', '_', slug)
    return slug


class UnboundImage(Exception):
    pass


def get_model_name(instance):
    T = type(instance)
    meta = T._meta
    return '{}.{}'.format(meta.app_label, meta.model_name)


PICTURE_LINK_FIELD = 'linked_object'


def upload_to(instance, fn):
    try:
        obj = getattr(instance, PICTURE_LINK_FIELD)
        if not isinstance(obj, models.Model):
            raise Exception('Not A Model')
        model_name = get_model_name(obj)
        id = obj.id
        return '{}/{}/{}'.format(model_name, id, slugify(fn))

    except Exception as ex:
        raise UnboundImage(
            'An image can not not belong to an object.\n{}'.format(ex))


class BasePicture(models.Model):
    class Meta:
        abstract = True

    id = models.AutoField(primary_key=True)

    file = ThumbnailerImageField(upload_to=upload_to)

    def __str__(self):
        return '{}'.format(self.file)

    # def tag(self):
    #     thumb_url = self.file.admin.url
    #     return mark_safe('<img src="{}" title="{}" />'.format(
    #         thumb_url, self.file.name))

    # tag.short_description = 'Image'


picture_models = dict()


def picture(model, **fields):
    meta = model._meta
    is_sorted = fields.pop('is_sorted', False)
    related_name = 'picture_{}'.format(meta.model_name)
    if related_name not in picture_models:
        class_name = 'Picture{}'.format(meta.model_name.capitalize())
        caption_name = 'picture_caption_{}'.format(meta.model_name)
        app_label = meta.app_label
        meta = type('Meta', (), dict(app_label=app_label))

        if is_sorted:
            meta = type('Meta', (),
                        dict(app_label=app_label, ordering=['sort_value']))
            fields['sort_value'] = models.IntegerField('Weight', default=0)

        fields.update(
            dict(
                Meta=meta,
                __module__='{}.models'.format(app_label),
                caption=message_field(caption_name),
                linked_object=models.ForeignKey(
                    model,
                    on_delete=models.CASCADE,
                    related_name=related_name,
                )), )
        picture_models[related_name] = type(class_name, (BasePicture, ),
                                            fields)

    return picture_models[related_name]


class EmbedMedia(models.Model):
    PROVIDERS = (
        ('youtube', 'Youtube'),
        ('vimeo', 'Vimeo'),
        ('roundme', 'RoundMe'),
    )

    id = models.AutoField(primary_key=True)
    tree = models.ForeignKey(to='Tree', on_delete=models.CASCADE)

    provider = models.CharField(
        max_length=12, choices=PROVIDERS, default='youtube')
    media_id = models.CharField(max_length=256)

wood/wood_core/models/subject.py
#  Copyright (C) 2018 Atelier Cartographique <contact@atelier-cartographique.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, version 3 of the License.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

from django.contrib.gis.db import models
from easy_thumbnails.fields import ThumbnailerImageField

from wood_lingua.models import message_field
from wood_botanique.models.species import Taxon

from .media import picture, slugify
from .ancillary import BaseLink


class TreeManager(models.Manager):
    def get_queryset(self):
        select = (
            'name',
            'description',
            'street_address',
            'city',
            'post_code',
        )
        return super().get_queryset().select_related(*select)


def upload_to_photomaton(instance, fn):
    id = instance.id
    return 'phototomaton/{}/{}'.format(id, slugify(fn))


class Tree(models.Model):
    objects = TreeManager()

    REMARQUABLE = 'rmqb'
    REMARQUE = 'rmqe'
    ADOPTE = 'adpt'
    CATEGORY = (
        (REMARQUABLE, 'Remarquable'),
        (REMARQUE, 'Remarqué'),
        (ADOPTE, 'Adopté'),
    )

    id = models.AutoField(primary_key=True)
    patrimoine = models.IntegerField(blank=True, null=True)
    import_id = models.CharField(max_length=12)
    category = models.CharField(max_length=4, choices=CATEGORY)
    taxon = models.ForeignKey(Taxon, on_delete=models.CASCADE)

    photomaton = ThumbnailerImageField(upload_to=upload_to_photomaton)

    name = message_field('tree_name')
    description = message_field('tree_description')

    street_address = message_field('tree_street_address')
    city = message_field('tree_city')
    post_code = message_field('tree_post_code')
    position = models.PointField(srid=4326)

    height = message_field('tree_height')
    circumference = message_field('tree_circumference')
    crown_diameter = message_field('tree_crown_diameter')

    def __str__(self):
        return '{} ({})'.format(self.name, self.id)


TreePicture = picture(Tree, is_sorted=True)


class Remarqueur(BaseLink):
    url = message_field('remarqueur_url')
    label = message_field('remarqueur_label')


class Activity(BaseLink):
    url = message_field('activity_url')
    label = message_field('activity_label')


class LinkedMedia(BaseLink):
    url = models.URLField()
    label = message_field('linked_media_label')


class Jumelage(BaseLink):
    BELGIQUE = 'belgique'
    EUROPE = 'europe'
    MONDE = 'monde'
    SCOPE = (
        (BELGIQUE, 'Belgique'),
        (EUROPE, 'Europe'),
        (MONDE, 'Monde'),
    )
    scope = models.CharField(max_length=12, choices=SCOPE)

    url = models.URLField()
    label = message_field('jumelage_label')

wood/wood_core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse
# from django.core.serializers import serialize
from shapely.geometry import Point
from django.urls import reverse
from pyproj import Proj, transform

from .models.subject import Tree, TreePicture
from .models.ancillary import Portrait
from wood_botanique.models.species import TaxonPicture

wgs = Proj(init='epsg:4326')
lambert72 = Proj(init='epsg:31370')


def front_page(request, lang):
    """Serve the landing page
    """
    template_name = 'wood_core/site-{}/index.html'.format(lang)
    context = {
        'lang': lang,
        'counter': Tree.objects.count(),
        'monthly': Portrait.objects.filter(monthly=True).first()
    }
    return render(request, template_name, context)


def about_page(request, lang):
    """Serve the landing page
    """
    template_name = 'wood_core/site-{}/about.html'.format(lang)
    context = {}
    return render(request, template_name, context)


def atlas_map(request, lang):
    """Serve the atlas map
    """
    template_name = 'wood_core/site-{}/map.html'.format(lang)
    context = {'lang': lang}
    return render(request, template_name, context)


class GeoAcc:
    features = []

    def push(self, coords, props):
        x, y = transform(wgs, lambert72, coords[0], coords[1])
        # print('> {} {}'.format(coords[0], coords[1]))
        # print('= {} {}'.format(x, y))
        p = Point([x, y]).buffer(10)
        self.features.append(
            dict(
                type='Feature',
                geometry=dict(
                    type="Polygon", coordinates=[list(p.exterior.coords)]),
                properties=props))

    def geojson(self):
        return dict(type="FeatureCollection", features=self.features)


def atlas_data(request):
    """Serve the atlas data
    """
    geo_acc = GeoAcc()
    for tree in Tree.objects.all():
        props = dict(
            category=tree.category,
            has_portrait=tree.portrait_set.count() > 0,
            nom_fr=tree.name.fr,
            nom_nl=tree.name.nl,
            famille_fr=tree.taxon.trivia.fr,
            famille_nl=tree.taxon.trivia.nl,
            adresse_1=tree.street_address.fr,
            adres_1=tree.street_address.nl,
            latin='{} {}'.format(tree.taxon.genus, tree.taxon.species),
            wood_file='atlas/{}.html'.format(tree.id),
        )
        geo_acc.push(tree.position.coords, props)

    return JsonResponse(geo_acc.geojson())


def atlas_page(request, lang, pid):
    """Serve an identification page for a tree
    """
    template_name = 'wood_core/fiche.html'
    obj = get_object_or_404(Tree, pk=pid)
    if 'rmqe' == obj.category:
        template_name = 'wood_core/fiche-rmq.html'
    context = {
        'tree': obj,
        'lang': lang,
        'media_sizes': (2000, 1800, 1600, 1400, 1200, 1000, 800, 600, 400),
    }
    return render(
        request,
        template_name,
        context,
    )


def atlas_pdf(request):
    """Serve an identification document (PDF) for a tree
    """
    pass


def get_size(w, h, target):
    if w > h:
        r = target / w
    else:
        r = target / h
    tw = w * r
    th = h * r
    return (tw, th)


def media(request, model, id, target):
    if 'treepicture' == model:
        obj = get_object_or_404(TreePicture, pk=id)
        width, height = get_size(obj.file.width, obj.file.height, target)
        thumb = obj.file.get_thumbnail({'size': [width, height]})
        return redirect(thumb.url, permanent=True)
    elif 'tree' == model:
        obj = get_object_or_404(Tree, pk=id)
        width, height = get_size(obj.photomaton.width, obj.photomaton.height,
                                 target)
        thumb = obj.photomaton.get_thumbnail({'size': [width, height]})
        return redirect(thumb.url, permanent=True)
    elif 'taxon' == model:
        obj = get_object_or_404(TaxonPicture, pk=id)
        width, height = get_size(obj.file.width, obj.file.height, target)
        thumb = obj.file.get_thumbnail({'size': [width, height]})
        return redirect(thumb.url, permanent=True)

wood/wood_core/templates/wood_core/bota.html
{% load wood %}
<div class="planche-bota-wrapper">
{% for picture in tree.taxon.picture_taxon.all %}
    <a href="{{ picture.file.url }}">
        <img src="{% url 'wood-media' 'taxon' picture.id 600 %}" alt="">
    </a>
    {% if picture.caption|tr:lang is not '' %}
    <div class="caption">
        {{ picture.caption|tr:lang }}
    </div>
    {% endif %} 
{% endfor %}
</div>

wood/wood_core/templates/wood_core/description-rmq.html
{% load wood %}

<!-- description -->
<div class="description">
    <h2>{% tr_label lang fr="Traits et caractères de l'arbre remarqué" nl="Kenmerken/Karakter van het bekende boom" %}</h2>
    <div class="item">
        <div class="content">
            <p>{{tree.description|tr:lang}}</p>
        </div>
    </div>
</div>

wood/wood_core/templates/wood_core/footer.html
{% load static %}
{% load wood %}

<div class="footer-atlas">
    <a href="{% url 'wood-index' lang %}"><img src="{% static 'wood_core/svg/www.svg' %}" alt="wood wide web"></a>
    <a href="{% url 'wood-index' lang %}#footer">{% tr_label lang fr="Contact & Newsletter" nl="Contact & Nieuwsbrief" %}</a>
    <a href="https://www.facebook.com/Arbres-bruxellois-283959091674027/" target="_blank"><img src="{% static 'wood_core/svg/fb-white.svg' %}"
            alt="woodwideweb on FB"></a>

    <div class="copyright">
        © 32shoot asbl
    </div>

    <div class="ac-credits">
        dev &amp; design :
        <a href="http://atelier-cartographique.be" title="atelier cartographique" target="_blank">a.-c.</a>
    </div>
</div>

wood/wood_core/templates/wood_core/identity-rmq.html
{% load wood %}


<!-- identity -->
<div class="identity">
    <h2>{% tr_label lang fr="Carte d'identité" nl="Identiteit" %}</h2>
    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en latin :" nl="Latijn :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.genus }} {{ tree.taxon.species }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en français :" nl="Namm FR :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.name.fr }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en néerlandais :" nl="Naam NL :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.name.nl }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en anglais :" nl="Naam EN :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.name.en }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Famille :" nl="Familie :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.family }}</span>
        </div>
    </div>


    <div class="item">
        <div class="label">{% tr_label lang fr="Hauteur visée :" nl="Beoogde hoogte :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.max_height|tr:lang }}</span>
        </div>
    </div>


    <div class="item">
        <div class="label">{% tr_label lang fr="Circonférence espérée :" nl="Verwachte omtrek :" %}</div>
        <div class="content">
            <span>{{ CIRCONFE_RENCE_ESPE_RE_E }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Longévité espérée :" nl="Verwachte levensduur :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.max_age|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Origine / Indigène :" nl="Oorsprong/Afkomst :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.origin|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Sol préféré :" nl="Voorkeursbodem :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.soil|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Climat préféré :" nl="Voorkeursklimaat :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.climate|tr:lang }}</span>
        </div>
    </div>
</div>
<!-- /identity -->

wood/wood_core/templates/wood_core/identity.html
{% load wood %}


<!-- identity -->
<div class="identity">
    <h2>{% tr_label lang fr="Carte d'identité" nl="Identiteit" %}</h2>
    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en latin :" nl="Latijn :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.genus }} {{ tree.taxon.species }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en français :" nl="Namm FR :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.name.fr }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en néerlandais :" nl="Naam NL :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.name.nl }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Nom en anglais :" nl="Naam EN :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.name.en }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Famille :" nl="Familie :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.family }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Hauteur :" nl="Hoogte :" %}</div>
        <div class="content">
            <span>{{ tree.height|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Hauteur visée :" nl="Beoogde hoogte :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.max_height|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Diamètre de la couronne :" nl="Diameter kruin :" %}</div>
        <div class="content">
            <span>{{ tree.crown_diameter|tr:lang }}</span>
        </div>
    </div>


    <div class="item">
        <div class="label">{% tr_label lang fr="Circonférence du tronc :" nl="Omtrek van de stam :" %}</div>
        <div class="content">
            <span>{{ tree.circumference|tr:lang }}</span>
        </div>
    </div>


    <div class="item">
        <div class="label">{% tr_label lang fr="Circonférence espérée :" nl="Verwachte omtrek :" %}</div>
        <div class="content">
            <span>{{ CIRCONFE_RENCE_ESPE_RE_E }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Longévité espérée :" nl="Verwachte levensduur :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.max_age|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Origine / Indigène :" nl="Oorsprong/Afkomst :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.origin|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Sol préféré :" nl="Voorkeursbodem :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.soil|tr:lang }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Climat préféré :" nl="Voorkeursklimaat :" %}</div>
        <div class="content">
            <span>{{ tree.taxon.climate|tr:lang }}</span>
        </div>
    </div>
</div>
<!-- /identity -->

wood/wood_core/templates/wood_core/linked-medias.html
{% load wood %}

<!-- linked-medias -->
{% if tree.linkedmedia_set.count > 0 %}
<div class="linked-medias">
    <h2>Médias liés</h2>
    {% for linked_media in tree.linkedmedia_set.all %}
    <li><a href="{{linked_media.url}}" target="_blank">{{ linked_media.label|tr:lang }}</a></li>
    {% endfor %}

</div>

{% endif %}

wood/wood_core/templates/wood_core/medias.html
{% load wood %}
<!-- attached-medias -->
<div class="media-collection">

    {% for media in tree|embed:'vimeo' %}
    <div class="media-video">
        <iframe 
            src="https://player.vimeo.com/video/{{media.media_id}}?title=0&amp;byline=0&amp;portrait=0"
            webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" class="video-v" frameborder="0"></iframe>
    </div>
    {% endfor %}

    {% for media in tree|embed:'youtube' %}
    <div class="media-video">
        <iframe width="100%" src="https://www.youtube.com/embed/{{media.media_id}}?rel=0&amp;showinfo=0" frameborder="0" gesture="media"
            allow="encrypted-media" allowfullscreen></iframe>
    </div>
    {% endfor %}

    {% for pic in tree.picture_tree.all %}
    <div class="media-image-wrapper">
        <style>
        {% for sz in media_sizes %}
        @media (max-width: {{sz}}px) {
            #pictree_{{pic.id}} {
                background-image: url("{% url 'wood-media' 'treepicture' pic.id sz %}");
                padding-top: {{ pic.file|ratio:sz }}%;
            }
        }
        {% endfor %}
        </style>
        <a href="{{pic.file.url}}">
            <div id="pictree_{{pic.id}}" class="media-image">
            </div>
            {% if pic.caption|tr:lang is not '' %}
            <div class="media-caption">{{caption_fr}}</div>
            {% endif %}
        </a>
    </div>
    {% endfor %}
</div>

wood/wood_core/templates/wood_core/photomaton.html
{% load wood %}
<!-- MAIN IMAGE -->
<section class="main-img">
    <style>
    {% for sz in media_sizes %}
        @media (max-width: {{sz}}px) {
            #photmaton_{{tree.id}} {
                background-image: url("{% url 'wood-media' 'tree' tree.id sz %}");
                padding-top: {{ tree.photomaton|ratio:sz }}%;
            }
        }
    {% endfor %}    
    </style>
    <div id="photmaton_{{tree.id}}" class="photomaton"></div>
</section>

wood/wood_core/templates/wood_core/portrait.html
{% load wood %}
<!-- PORTRAIT -->
{% for p in tree.portrait_set.all %}
<div class="portrait">
    {{ p.body|tr:lang|md }}
</div>
{% endfor %}

wood/wood_core/templates/wood_core/situation-rmq.html
{% load wood %}

<!-- address -->
<div class="address">
    <div class="item">
        <div class="label">{% tr_label lang fr="Adresse :" nl="Adres :" %}</div>
        <div class="content">
            <span>{{ tree.street_address|tr:lang }}</span>
            <span> </span>
            <span>{{ tree.city|tr:lang }}</span>
        </div>
    </div>

    {% if tree.category == 'rmqe' %}
    <div class="item">
        <div class="label">Partenaire :</div>
        <div class="content">
            <span>{% tr_label lang fr="Cet arbre a été ajouté à l’atlas de Wood Wide Web par" nl="Deze boom is toegevoegd aan de Wood Wide Web atlas door"%}</span>
            <span> </span>
            {% for r in tree.remarqueur_set.all %}
            {% if r.url|tr:lang is not '' %}
            <span> <a href="{{ r.url|tr:lang }}">{{ r.label|tr:lang }}</a> </span>
            {% else %}
            <span>{{ r.label|tr:lang }}</span>
            {% endif %}
            
            {% endfor %}
        </div>
    </div>
    {% endif %}

</div>

wood/wood_core/templates/wood_core/situation.html
{% load wood %}

<!-- address -->
<div class="address">
    <div class="item">
        <div class="label">{% tr_label lang fr="Adresse :" nl="Adres :" %}</div>
        <div class="content">
            <span>{{ tree.street_address|tr:lang }}</span>
            <span> </span>
            <span>{{ tree.city|tr:lang }}</span>
        </div>
    </div>



    <div class="item">
        <div class="label">{% tr_label lang fr="Coordonnées GPS :" nl="Gps-coörd. :" %}</div>
        <div class="content">
            <span>{{ tree.position.coords.0 }}</span>
            <span>, {{ tree.position.coords.1 }}</span>
        </div>
    </div>

    <div class="item">
        <div class="label">{% tr_label lang fr="Inventaire scientifique :" nl="Wetenschappelijke inventarisatie :" %}</div>
        <div class="content">
            <span><a href="http://{% tr_label lang fr="arbres-inventaire" nl="bomen-inventaris" %}.irisnet.be/tree.php?id={{tree.patrimoine}}">{{tree.patrimoine}}</a></span>
        </div>
    </div>

    {% comment "Not implemented" %}
    <div class="item">
        <div class="label">Coordonnées Lambert :</div>
        <div class="content">
            <span>{{ LAMBERT_1 }}</span>
            <span>, {{ LAMBERT_2 }}</span>
        </div>
    </div>
    {% endcomment %}


</div>

wood/wood_core/templates/wood_core/title.html
{% load wood %}

<!-- BLOCK TITLE -->

<div class="block-title">
    <h1>
        {{ tree.name|tr:lang }}
        <!-- {{ tree.street_address|tr:lang }} -->
    </h1>
</div>

wood/wood_core/templates/wood_core/twins.html
{% load wood %}
<!-- twinning -->
{% if tree.jumelage_set.all|length > 0 %}
<div class="twinning">
    <h2>{% tr_label lang fr="Arbres liés - jumelage" nl="Als u van dit soort boom houdt, zult u ook houden van In Brussel" %}</h2>
    <div class="belgique">
        <p>Belgique</p>
        {% for jum in tree|jumelage:'belgique' %}
        <li><a href="{{jum.url}}" target="_blank">{{jum.label|tr:lang}}</a></li>
        {% endfor %}
    </div>
    <div class="europe">
        <p>Union Européenne</p> 
        {% for jum in tree|jumelage:'europe' %}
        <li><a href="{{jum.url}}" target="_blank">{{jum.label|tr:lang}}</a></li>
        {% endfor %}
    </div>
    <div class="monde">
        <p>Monde</p>
        {% for jum in tree|jumelage:'monde' %}
        <li><a href="{{jum.url}}" target="_blank">{{jum.label|tr:lang}}</a></li>
        {% endfor %}
    </div>

</div>
{% endif %}